{% set name = "piso" %}
{% set version = "0.9.0" %}
{% set sha = "2eb3f2c6772789f6f2401d0b967cb676e0c8feadf559ff7172b65547081a2612" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6.1
    - pip
    - poetry
  run:
    - python >=3.6.1,<4
    - pandas >=1,<2
    - numpy >=1.16.0,<2
    - staircase >=2.1.0,<3

test:
  imports:
    - piso

about:
  home: https://github.com/staircase-dev/piso
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'piso: pandas interval set operations'
  description: |
    Pandas Interval Set Operations: providing methods for set operations, analytics, lookups and joins on pandas' Interval, IntervalArray and IntervalIndex
  doc_url: https://piso.readthedocs.io/
  dev_url: https://github.com/staircase-dev/piso

extra:
  recipe-maintainers:
    - staircase-dev
    - venaturum
