{% set name = "piso" %}
{% set version = "0.4.0" %}
{% set sha = "494c5549b89b15d6f92f12e95bbdfb080e3e599a568c875f3bec2a09752419fb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6.1
    - pip <21.3
    - poetry
  run:
    - python >=3.6.1,<4
    - pandas >=1,<2
    - numpy >=1.16.0,<2
    - staircase >=2.0.4,<3

test:
  imports:
    - piso

about:
  home: https://github.com/staircase-dev/piso
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'piso: pandas interval set operations'
  description: |
    Pandas Interval Set Operations: providing methods for set operations (union, intersection, difference + more) for pandas' Interval, IntervalArray, and IntervalIndex
  doc_url: https://piso.readthedocs.io/
  dev_url: https://github.com/staircase-dev/piso

extra:
  recipe-maintainers:
    - staircase-dev
    - venaturum
