{% set name = "piso" %}
{% set version = "1.2.0" %}
{% set sha = "1453ad71141e1653e7d79cf1f73a2226f62c28311a9c0c8f0cf3603a17a72d6c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - poetry
  run:
    - python >=3.8,<4
    - pandas >=1,<3
    - numpy >=1.17.0,<2
    - staircase >=2.1.0,<3

test:
  imports:
    - piso

about:
  home: https://github.com/staircase-dev/piso
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'piso: pandas interval set operations'
  description: |
    Pandas Interval Set Operations: providing methods for set operations, analytics, lookups and joins on pandas' Interval, IntervalArray and IntervalIndex
  doc_url: https://piso.readthedocs.io/
  dev_url: https://github.com/staircase-dev/piso

extra:
  recipe-maintainers:
    - staircase-dev
    - venaturum
